### ISSUE TITLE
User list sliding menu can be opened from main fragment

### ISSUE THREAD

**Issue by zacharee** [HueToYou/ChatExchange#2]
Selecting a chat, then pressing back or the back arrow in the app to get back to the home fragment allows the users sliding menu to be dragged out.

**Comment by UsernameInvalidException** [comment]
Yeah, I knew about this one for a while. I _think_ I know how to fix it...

**Comment by zacharee** [comment]
I know you knew. You told me about it.

**Comment by UsernameInvalidException** [comment]
Fixed in 8511fd6
