### ISSUE TITLE
User tiles are duplicated when theme is switched

### ISSUE THREAD

**Issue by UsernameInvalidException** [HueToYou/ChatExchange#4]
![screenshot_20170628-140458](https://user-images.githubusercontent.com/28464769/27653145-2b73554c-5c0c-11e7-9b57-0bdf376cd990.png)

See above screenshot.
Procedure to reproduce:

1. Close out and re-open the app
2. Open any chatroom you want
3. Open & close the users sliding menu
4. Open settings
5. Switch the theme
6. Exit settings
7. Open the users sliding menu. All tiles will now be duplicated.

**Comment by UsernameInvalidException** [comment]
@zacharee Well you didn't completely fix this in you new commit. Now they aren't duplicated, but sometimes they all disappear!

**Comment by zacharee** [comment]
Closing for now as it seems to be fixed.
