### ISSUE TITLE
Users panel cannot be opened by swiping after switching theme

### ISSUE THREAD

**Issue by UsernameInvalidException** [HueToYou/ChatExchange#6]
Title says it all. If the theme is switched without reloading the app, the users sliding panel cannot be opened by swiping

**Comment by zacharee** [comment]
You seem to have fixed this.

**Comment by UsernameInvalidException** [comment]
Nooo.... it came back :\

**Comment by zacharee** [comment]
Maybe back, maybe not. This is a weird bug.

**Comment by UsernameInvalidException** [comment]
I haven't seen this bug again. Let's leave this open for a bit longer though

**Comment by UsernameInvalidException** [comment]
Well, I haven't had this happen since. I'm closing it again :D
